title: Luca Wellmeier
author:
  name: Luca Wellmeier
  email: lucwellm@gmail.com
description: >
  blog about my thesis

show_excerpts: true
excerpt_separator: <!--more-->

baseurl: "/masters-thesis"
url: "https://lucawellmeier.github.io"

minima:
  date_format: "%b %-d, %Y"
  social_links:
    github: lucawellmeier

markdown: kramdown
kramdown:
    math_engine: katex

highlighter: rouge
